[2022-06-11 10:31:02,853] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 10:31:02,854] [builder.py:185]            [INFO]     |                                 Trakt Watched Collection in Movies                                 |
[2022-06-11 10:31:02,855] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 10:31:02,855] [builder.py:186]            [INFO]     |                                                                                                    |
[2022-06-11 10:31:02,856] [builder.py:191]            [INFO]     |=============================== Validating Trakt Watched Attributes ================================|
[2022-06-11 10:31:02,856] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:02,857] [builder.py:213]            [DEBUG]    | Validating Method: template                                                                        |
[2022-06-11 10:31:02,857] [meta.py:103]               [DEBUG]    | Value: [{'value': ['watched'], 'custom': ['watched'], 'key_name': 'Watched', 'key': 'watched', 'name': 'trakt'}, {'value': ['watched'], 'custom': ['watched'], 'key_name': 'Watched', 'key': 'watched', 'name': 'customsync'}, {'value': ['watched'], 'custom': ['watched'], 'key_name': 'Watched', 'key': 'watched', 'name': 'chart_shared'}] |
[2022-06-11 10:31:02,861] [builder.py:437]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:02,862] [builder.py:438]            [DEBUG]    | Validating Method: sync_mode                                                                       |
[2022-06-11 10:31:02,862] [builder.py:442]            [DEBUG]    | Value: sync                                                                                        |
[2022-06-11 10:31:02,863] [builder.py:582]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:02,863] [builder.py:583]            [DEBUG]    | Validating Method: collection_order                                                                |
[2022-06-11 10:31:02,863] [builder.py:584]            [DEBUG]    | Value: custom                                                                                      |
[2022-06-11 10:31:02,864] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:02,864] [builder.py:604]            [DEBUG]    | Validating Method: label                                                                           |
[2022-06-11 10:31:02,864] [builder.py:605]            [DEBUG]    | Value: Trakt                                                                                       |
[2022-06-11 10:31:02,865] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:02,865] [builder.py:604]            [DEBUG]    | Validating Method: trakt_chart                                                                     |
[2022-06-11 10:31:02,865] [builder.py:605]            [DEBUG]    | Value: {'chart': 'watched', 'limit': 100}                                                          |
[2022-06-11 10:31:02,866] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:02,866] [builder.py:604]            [DEBUG]    | Validating Method: summary                                                                         |
[2022-06-11 10:31:02,866] [builder.py:605]            [DEBUG]    | Value: A collection of Trakt's Weekly movie List                                                   |
[2022-06-11 10:31:02,867] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:02,867] [builder.py:604]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-06-11 10:31:02,867] [builder.py:605]            [DEBUG]    | Value: !01_Trakt Watched                                                                           |
[2022-06-11 10:31:02,867] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:02,868] [builder.py:604]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-06-11 10:31:02,868] [builder.py:605]            [DEBUG]    | Value: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/chart/Trakt%20Watched.jpg |
[2022-06-11 10:31:03,454] [plex.py:742]               [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:03,790] [plex.py:745]               [DEBUG]    | Looking for: Trakt Watched                                                                         |
[2022-06-11 10:31:03,790] [builder.py:764]            [INFO]     |                                                                                                    |
[2022-06-11 10:31:03,791] [builder.py:765]            [INFO]     | Validation Successful                                                                              |
[2022-06-11 10:31:03,791] [plex_meta_manager.py:539]  [INFO]     |                                                                                                    |
[2022-06-11 10:31:03,792] [plex_meta_manager.py:541]  [INFO]     |================================= Running Trakt Watched Collection =================================|
[2022-06-11 10:31:03,793] [plex_meta_manager.py:553]  [INFO]     |                                                                                                    |
[2022-06-11 10:31:03,793] [plex_meta_manager.py:554]  [INFO]     | Sync Mode: sync                                                                                    |
[2022-06-11 10:31:03,794] [plex_meta_manager.py:557]  [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:03,795] [plex_meta_manager.py:558]  [DEBUG]    | Builder: trakt_chart: {'chart': 'watched', 'limit': 100, 'time_period': None}                      |
[2022-06-11 10:31:03,795] [plex_meta_manager.py:559]  [INFO]     |                                                                                                    |
[2022-06-11 10:31:03,796] [trakt.py:490]              [INFO]     | Processing Trakt Chart: 100 Watched Movies                                                         |
[2022-06-11 10:31:04,464] [builder.py:1507]           [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:04,468] [builder.py:1508]           [DEBUG]    | 100 IDs Found: [(361743, 'tmdb'), (338953, 'tmdb'), (507086, 'tmdb'), (752623, 'tmdb'), (961484, 'tmdb'), (526896, 'tmdb'), (675353, 'tmdb'), (648579, 'tmdb'), (809140, 'tmdb'), (453395, 'tmdb'), (639933, 'tmdb'), (744, 'tmdb'), (818397, 'tmdb'), (414906, 'tmdb'), (831946, 'tmdb'), (545611, 'tmdb'), (335787, 'tmdb'), (629542, 'tmdb'), (974691, 'tmdb'), (763285, 'tmdb'), (634649, 'tmdb'), (420821, 'tmdb'), (628900, 'tmdb'), (810171, 'tmdb'), (351286, 'tmdb'), (705861, 'tmdb'), (532710, 'tmdb'), (135397, 'tmdb'), (957258, 'tmdb'), (406759, 'tmdb'), (293660, 'tmdb'), (438631, 'tmdb'), (568124, 'tmdb'), (22, 'tmdb'), (508947, 'tmdb'), (329, 'tmdb'), (338952, 'tmdb'), (800937, 'tmdb'), (118340, 'tmdb'), (505026, 'tmdb'), (820446, 'tmdb'), (674, 'tmdb'), (259316, 'tmdb'), (284052, 'tmdb'), (438695, 'tmdb'), (696806, 'tmdb'), (58, 'tmdb'), (157336, 'tmdb'), (566525, 'tmdb'), (671, 'tmdb'), (155, 'tmdb'), (843633, 'tmdb'), (760104, 'tmdb'), (476669, 'tmdb'), (19995, 'tmdb'), (370172, 'tmdb'), (624860, 'tmdb'), (299534, 'tmdb'), (550988, 'tmdb'), (28844, 'tmdb'), (661231, 'tmdb'), (524434, 'tmdb'), (823625, 'tmdb'), (24428, 'tmdb'), (299536, 'tmdb'), (626735, 'tmdb'), (767, 'tmdb'), (672, 'tmdb'), (425909, 'tmdb'), (580489, 'tmdb'), (27205, 'tmdb'), (978278, 'tmdb'), (1726, 'tmdb'), (330, 'tmdb'), (283995, 'tmdb'), (846250, 'tmdb'), (864116, 'tmdb'), (150540, 'tmdb'), (109445, 'tmdb'), (28682, 'tmdb'), (973164, 'tmdb'), (799876, 'tmdb'), (120, 'tmdb'), (285, 'tmdb'), (829557, 'tmdb'), (11, 'tmdb'), (278, 'tmdb'), (603, 'tmdb'), (284053, 'tmdb'), (50620, 'tmdb'), (673, 'tmdb'), (656663, 'tmdb'), (315635, 'tmdb'), (245891, 'tmdb'), (277834, 'tmdb'), (785985, 'tmdb'), (1895, 'tmdb'), (858015, 'tmdb'), (271110, 'tmdb'), (140607, 'tmdb')] |
[2022-06-11 10:31:04,469] [builder.py:1509]           [DEBUG]    |                                                                                                    |
[2022-06-11 10:31:04,474] [builder.py:2009]           [INFO]     |                                                                                                    |
[2022-06-11 10:31:04,475] [builder.py:2010]           [INFO]     |================================ Adding to Trakt Watched Collection ================================|
[2022-06-11 10:31:04,476] [builder.py:2011]           [INFO]     |                                                                                                    |
[2022-06-11 10:31:04,476] [builder.py:2025]           [INFO]     | 1/9 | Trakt Watched Collection | + | Pirates of the Caribbean: The Curse of the Black Pearl (2003) |
[2022-06-11 10:31:12,804] [builder.py:2025]           [INFO]     | 2/9 | Trakt Watched Collection | + | Sing 2 (2021)                                                 |
[2022-06-11 10:31:17,319] [builder.py:2025]           [INFO]     | 3/9 | Trakt Watched Collection | + | Shang-Chi and the Legend of the Ten Rings (2021)              |
[2022-06-11 10:32:17,390] [plex_meta_manager.py:668]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
                                                                 |     six.raise_from(e, None)
                                                                 |   File "<string>", line 3, in raise_from
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
                                                                 |     httplib_response = conn.getresponse()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 1386, in getresponse
                                                                 |     response.begin()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 312, in begin
                                                                 |     version, status, reason = self._read_status()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 273, in _read_status
                                                                 |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                                 |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
                                                                 |     return self._sock.recv_into(b)
                                                                 | socket.timeout: timed out
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
                                                                 |     resp = conn.urlopen(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
                                                                 |     retries = retries.increment(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
                                                                 |     raise six.reraise(type(error), error, _stacktrace)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
                                                                 |     raise value
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
                                                                 |     httplib_response = self._make_request(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
                                                                 |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
                                                                 |     raise ReadTimeoutError(
                                                                 | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "plex_meta_manager.py", line 570, in run_collection
                                                                 |     items_added, items_unchanged = builder.add_to_collection()
                                                                 |   File "/root/Plex-Meta-Manager/modules/builder.py", line 2032, in add_to_collection
                                                                 |     self.library.alter_collection(item, name, smart_label_collection=self.smart_label_collection)
                                                                 |   File "/root/Plex-Meta-Manager/modules/plex.py", line 650, in alter_collection
                                                                 |     field = next((f for f in item.fields if f.name == "collection"), None)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 483, in __getattribute__
                                                                 |     self._reload(_overwriteNone=False)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 357, in _reload
                                                                 |     data = self._server.query(key)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/server.py", line 696, in query
                                                                 |     response = method(url, headers=headers, timeout=timeout, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
                                                                 |     return self.request('GET', url, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
                                                                 |     resp = self.send(prep, **send_kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
                                                                 |     r = adapter.send(request, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
                                                                 |     raise ReadTimeout(e, request=request)
                                                                 | requests.exceptions.ReadTimeout: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
[2022-06-11 10:32:17,717] [plex_meta_manager.py:669]  [ERROR]    | Unknown Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
[2022-06-11 10:32:17,718] [plex_meta_manager.py:674]  [INFO]     | 
[2022-06-11 10:32:17,719] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
[2022-06-11 10:32:17,720] [plex_meta_manager.py:675]  [INFO]     |                                 Finished Trakt Watched Collection                                  |
[2022-06-11 10:32:17,720] [plex_meta_manager.py:675]  [INFO]     |                                    Collection Run Time: 0:01:14                                    |
[2022-06-11 10:32:17,720] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
