[2022-06-10 20:31:30,267] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-10 20:31:30,268] [builder.py:185]            [INFO]     |                        United States of America Collection in ....TV Shows                         |
[2022-06-10 20:31:30,268] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-10 20:31:30,269] [builder.py:186]            [INFO]     |                                                                                                    |
[2022-06-10 20:31:30,269] [builder.py:191]            [INFO]     |========================== Validating United States of America Attributes ==========================|
[2022-06-10 20:31:30,270] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:30,270] [builder.py:213]            [DEBUG]    | Validating Method: template                                                                        |
[2022-06-10 20:31:30,271] [meta.py:103]               [DEBUG]    | Value: [{'value': ['us'], 'origin_country': ['us'], 'key_name': 'United States of America', 'key': 'us', 'name': 'country_tv_dynamic'}, {'value': ['us'], 'origin_country': ['us'], 'key_name': 'United States of America', 'key': 'us', 'name': 'shared'}] |
[2022-06-10 20:31:30,275] [builder.py:582]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:30,276] [builder.py:583]            [DEBUG]    | Validating Method: collection_order                                                                |
[2022-06-10 20:31:30,276] [builder.py:584]            [DEBUG]    | Value: release.desc                                                                                |
[2022-06-10 20:31:30,276] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:30,277] [builder.py:604]            [DEBUG]    | Validating Method: label                                                                           |
[2022-06-10 20:31:30,277] [builder.py:605]            [DEBUG]    | Value: TMDb Country Color                                                                          |
[2022-06-10 20:31:30,277] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:30,278] [builder.py:604]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-06-10 20:31:30,278] [builder.py:605]            [DEBUG]    | Value: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/country/white/United%20States%20of%20America.jpg |
[2022-06-10 20:31:31,152] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:31,153] [builder.py:604]            [DEBUG]    | Validating Method: plex_all                                                                        |
[2022-06-10 20:31:31,153] [builder.py:605]            [DEBUG]    | Value: True                                                                                        |
[2022-06-10 20:31:31,154] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:31,155] [builder.py:604]            [DEBUG]    | Validating Method: filters                                                                         |
[2022-06-10 20:31:31,155] [builder.py:605]            [DEBUG]    | Value: {'origin_country': ['us']}                                                                  |
[2022-06-10 20:31:31,157] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:31,157] [builder.py:604]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-06-10 20:31:31,158] [builder.py:605]            [DEBUG]    | Value: !09_United States of America                                                                |
[2022-06-10 20:31:31,172] [plex.py:742]               [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:31,173] [plex.py:745]               [DEBUG]    | Looking for: United States of America                                                              |
[2022-06-10 20:31:31,173] [builder.py:764]            [INFO]     |                                                                                                    |
[2022-06-10 20:31:31,173] [builder.py:765]            [INFO]     | Validation Successful                                                                              |
[2022-06-10 20:31:31,174] [plex_meta_manager.py:539]  [INFO]     |                                                                                                    |
[2022-06-10 20:31:31,174] [plex_meta_manager.py:541]  [INFO]     |=========================== Running United States of America Collection ============================|
[2022-06-10 20:31:31,175] [plex_meta_manager.py:553]  [INFO]     |                                                                                                    |
[2022-06-10 20:31:31,175] [plex_meta_manager.py:554]  [INFO]     | Sync Mode: append                                                                                  |
[2022-06-10 20:31:31,175] [plex_meta_manager.py:557]  [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:31,176] [plex_meta_manager.py:558]  [DEBUG]    | Builder: plex_all: show                                                                            |
[2022-06-10 20:31:31,176] [plex_meta_manager.py:559]  [INFO]     |                                                                                                    |
[2022-06-10 20:31:31,177] [plex.py:760]               [INFO]     | Processing Plex All Shows                                                                          |
[2022-06-10 20:31:31,177] [plex.py:471]               [INFO]     | Loading All Shows from Library: ....TV Shows                                                       |
[2022-06-10 20:31:31,389] [plex.py:480]               [INFO]     | Loaded 24 Shows                                                                                    |
[2022-06-10 20:31:31,390] [plex.py:813]               [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:31,391] [plex.py:814]               [DEBUG]    | 24 Keys Found: [(72569, 'ratingKey'), (214877, 'ratingKey'), (281126, 'ratingKey'), (72510, 'ratingKey'), (31194, 'ratingKey'), (68199, 'ratingKey'), (280803, 'ratingKey'), (72524, 'ratingKey'), (33951, 'ratingKey'), (30191, 'ratingKey'), (279458, 'ratingKey'), (74086, 'ratingKey'), (34088, 'ratingKey'), (74009, 'ratingKey'), (274611, 'ratingKey'), (279438, 'ratingKey'), (279450, 'ratingKey'), (74049, 'ratingKey'), (74031, 'ratingKey'), (67478, 'ratingKey'), (67592, 'ratingKey'), (67611, 'ratingKey'), (279466, 'ratingKey'), (67419, 'ratingKey')] |
[2022-06-10 20:31:31,392] [builder.py:1507]           [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:31,392] [builder.py:1508]           [DEBUG]    | 24 IDs Found: [(72569, 'ratingKey'), (214877, 'ratingKey'), (281126, 'ratingKey'), (72510, 'ratingKey'), (31194, 'ratingKey'), (68199, 'ratingKey'), (280803, 'ratingKey'), (72524, 'ratingKey'), (33951, 'ratingKey'), (30191, 'ratingKey'), (279458, 'ratingKey'), (74086, 'ratingKey'), (34088, 'ratingKey'), (74009, 'ratingKey'), (274611, 'ratingKey'), (279438, 'ratingKey'), (279450, 'ratingKey'), (74049, 'ratingKey'), (74031, 'ratingKey'), (67478, 'ratingKey'), (67592, 'ratingKey'), (67611, 'ratingKey'), (279466, 'ratingKey'), (67419, 'ratingKey')] |
[2022-06-10 20:31:31,393] [builder.py:1509]           [DEBUG]    |                                                                                                    |
[2022-06-10 20:31:32,254] [builder.py:2151]           [WARNING]  | Filter Error: No TVDb ID found for Best of Phua Chu Kang Pte Ltd                                   |
[2022-06-10 20:31:43,412] [builder.py:2151]           [WARNING]  | Filter Error: No TVDb ID found for 信不信由你                                                           |
[2022-06-10 20:31:45,920] [builder.py:2151]           [WARNING]  | Filter Error: No TVDb ID found for 娱乐插班生                                                           |
[2022-06-10 20:31:46,562] [builder.py:2151]           [WARNING]  | Filter Error: No TVDb ID found for 富貴超人                                                            |
[2022-06-10 20:31:46,917] [builder.py:2151]           [WARNING]  | Filter Error: No TVDb ID found for 洪武大案                                                            |
[2022-06-10 20:31:50,066] [builder.py:2151]           [WARNING]  | Filter Error: No TVDb ID found for 龍影俠                                                             |
[2022-06-10 20:31:50,717] [plex_meta_manager.py:563]  [INFO]     |                                                                                                    |
[2022-06-10 20:31:50,718] [plex_meta_manager.py:567]  [INFO]     | Collection Filter origin_country: ['US']                                                           |
[2022-06-10 20:31:50,718] [builder.py:2009]           [INFO]     |                                                                                                    |
[2022-06-10 20:31:50,719] [builder.py:2010]           [INFO]     |========================== Adding to United States of America Collection ===========================|
[2022-06-10 20:31:50,719] [builder.py:2011]           [INFO]     |                                                                                                    |
[2022-06-10 20:31:50,720] [builder.py:2025]           [INFO]     | 1/7 | United States of America Collection | + | Curb Your Enthusiasm                               |
[2022-06-10 20:32:21,408] [builder.py:2025]           [INFO]     | 2/7 | United States of America Collection | + | Glee                                               |
[2022-06-10 20:32:46,115] [builder.py:2025]           [INFO]     | 3/7 | United States of America Collection | + | High School Musical: The Musical: The Series       |
[2022-06-10 20:32:47,217] [builder.py:2025]           [INFO]     | 4/7 | United States of America Collection | + | Last Week Tonight with John Oliver                 |
[2022-06-10 20:32:47,391] [builder.py:2025]           [INFO]     | 5/7 | United States of America Collection | + | Malcolm in the Middle                              |
[2022-06-10 20:32:49,025] [builder.py:2025]           [INFO]     | 6/7 | United States of America Collection | + | Most Dangerous Game                                |
[2022-06-10 20:32:51,899] [builder.py:2025]           [INFO]     | 7/7 | United States of America Collection | + | Warrior                                            |
[2022-06-10 20:32:53,892] [builder.py:2045]           [INFO]     |                                                                                                    |
[2022-06-10 20:32:53,893] [builder.py:2046]           [INFO]     | 7 Shows Processed                                                                                  |
[2022-06-10 20:32:54,063] [builder.py:2383]           [INFO]     |                                                                                                    |
[2022-06-10 20:32:54,064] [builder.py:2384]           [INFO]     |===================== Updating Details of United States of America Collection ======================|
[2022-06-10 20:32:54,064] [builder.py:2385]           [INFO]     |                                                                                                    |
[2022-06-10 20:33:54,606] [plex_meta_manager.py:668]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
                                                                 |     six.raise_from(e, None)
                                                                 |   File "<string>", line 3, in raise_from
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
                                                                 |     httplib_response = conn.getresponse()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 1386, in getresponse
                                                                 |     response.begin()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 312, in begin
                                                                 |     version, status, reason = self._read_status()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 273, in _read_status
                                                                 |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                                 |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
                                                                 |     return self._sock.recv_into(b)
                                                                 | socket.timeout: timed out
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
                                                                 |     resp = conn.urlopen(
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
                                                                 |     retries = retries.increment(
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
                                                                 |     raise six.reraise(type(error), error, _stacktrace)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
                                                                 |     raise value
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
                                                                 |     httplib_response = self._make_request(
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
                                                                 |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
                                                                 |     raise ReadTimeoutError(
                                                                 | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/root/Plex-Meta-Manager/plex_meta_manager.py", line 620, in run_collection
                                                                 |     details_list = builder.update_details()
                                                                 |   File "/root/Plex-Meta-Manager/modules/builder.py", line 2442, in update_details
                                                                 |     tag_results = self.library.edit_tags('label', self.obj, add_tags=add_tags, remove_tags=remove_tags, sync_tags=sync_tags, do_print=False)[28:]
                                                                 |   File "/root/Plex-Meta-Manager/modules/plex.py", line 875, in edit_tags
                                                                 |     _item_tags = [item_tag.tag for item_tag in getattr(obj, key)]
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/plexapi/base.py", line 483, in __getattribute__
                                                                 |     self._reload(_overwriteNone=False)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/plexapi/base.py", line 357, in _reload
                                                                 |     data = self._server.query(key)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/plexapi/server.py", line 696, in query
                                                                 |     response = method(url, headers=headers, timeout=timeout, **kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
                                                                 |     return self.request('GET', url, **kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
                                                                 |     resp = self.send(prep, **send_kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
                                                                 |     r = adapter.send(request, **kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
                                                                 |     raise ReadTimeout(e, request=request)
                                                                 | requests.exceptions.ReadTimeout: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
[2022-06-10 20:33:54,622] [plex_meta_manager.py:669]  [ERROR]    | Unknown Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
[2022-06-10 20:33:54,622] [plex_meta_manager.py:674]  [INFO]     | 
[2022-06-10 20:33:54,624] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
[2022-06-10 20:33:54,624] [plex_meta_manager.py:675]  [INFO]     |                            Finished United States of America Collection                            |
[2022-06-10 20:33:54,624] [plex_meta_manager.py:675]  [INFO]     |                                    Collection Run Time: 0:02:24                                    |
[2022-06-10 20:33:54,625] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
