[2022-06-11 14:36:52,578] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 14:36:52,579] [builder.py:185]            [INFO]     |                               TMDb Popular Collection in ..Cartoons                                |
[2022-06-11 14:36:52,580] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 14:36:52,580] [builder.py:186]            [INFO]     |                                                                                                    |
[2022-06-11 14:36:52,581] [builder.py:191]            [INFO]     |================================ Validating TMDb Popular Attributes ================================|
[2022-06-11 14:36:52,581] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2022-06-11 14:36:52,582] [builder.py:213]            [DEBUG]    | Validating Method: template                                                                        |
[2022-06-11 14:36:52,582] [meta.py:103]               [DEBUG]    | Value: [ordereddict([('name', 'popular')]), ordereddict([('name', 'customsync')]), ordereddict([('name', 'chart_shared'), ('key', 'popular')])] |
[2022-06-11 14:36:52,588] [builder.py:437]            [DEBUG]    |                                                                                                    |
[2022-06-11 14:36:52,589] [builder.py:438]            [DEBUG]    | Validating Method: sync_mode                                                                       |
[2022-06-11 14:36:52,589] [builder.py:442]            [DEBUG]    | Value: sync                                                                                        |
[2022-06-11 14:36:52,590] [builder.py:582]            [DEBUG]    |                                                                                                    |
[2022-06-11 14:36:52,590] [builder.py:583]            [DEBUG]    | Validating Method: collection_order                                                                |
[2022-06-11 14:36:52,590] [builder.py:584]            [DEBUG]    | Value: custom                                                                                      |
[2022-06-11 14:36:52,591] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 14:36:52,591] [builder.py:604]            [DEBUG]    | Validating Method: tmdb_popular                                                                    |
[2022-06-11 14:36:52,592] [builder.py:605]            [DEBUG]    | Value: 100                                                                                         |
[2022-06-11 14:36:52,592] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 14:36:52,593] [builder.py:604]            [DEBUG]    | Validating Method: summary                                                                         |
[2022-06-11 14:36:52,593] [builder.py:605]            [DEBUG]    | Value: A collection of the most watched shows according to TMDb.                                   |
[2022-06-11 14:36:52,594] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 14:36:52,594] [builder.py:604]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-06-11 14:36:52,595] [builder.py:605]            [DEBUG]    | Value: !01_TMDb Popular                                                                            |
[2022-06-11 14:36:52,595] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 14:36:52,596] [builder.py:604]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-06-11 14:36:52,596] [builder.py:605]            [DEBUG]    | Value: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/chart/TMDb%20Popular.jpg |
[2022-06-11 14:36:55,669] [builder.py:764]            [INFO]     |                                                                                                    |
[2022-06-11 14:36:55,670] [builder.py:765]            [INFO]     | Validation Successful                                                                              |
[2022-06-11 14:36:55,670] [plex_meta_manager.py:539]  [INFO]     |                                                                                                    |
[2022-06-11 14:36:55,671] [plex_meta_manager.py:541]  [INFO]     |================================= Running TMDb Popular Collection ==================================|
[2022-06-11 14:36:55,672] [plex_meta_manager.py:553]  [INFO]     |                                                                                                    |
[2022-06-11 14:36:55,672] [plex_meta_manager.py:554]  [INFO]     | Sync Mode: sync                                                                                    |
[2022-06-11 14:36:55,672] [plex_meta_manager.py:557]  [DEBUG]    |                                                                                                    |
[2022-06-11 14:36:55,673] [plex_meta_manager.py:558]  [DEBUG]    | Builder: tmdb_popular: 100                                                                         |
[2022-06-11 14:36:55,673] [plex_meta_manager.py:559]  [INFO]     |                                                                                                    |
[2022-06-11 14:36:56,007] [tmdb.py:344]               [INFO]     | Processing TMDb Popular: 100 Shows                                                                 |
[2022-06-11 14:36:56,008] [builder.py:1507]           [DEBUG]    |                                                                                                    |
[2022-06-11 14:36:56,008] [builder.py:1508]           [DEBUG]    | 100 IDs Found: [(66732, 'tmdb_show'), (76479, 'tmdb_show'), (92830, 'tmdb_show'), (52814, 'tmdb_show'), (49608, 'tmdb_show'), (62348, 'tmdb_show'), (89491, 'tmdb_show'), (154300, 'tmdb_show'), (158415, 'tmdb_show'), (92749, 'tmdb_show'), (60574, 'tmdb_show'), (157936, 'tmdb_show'), (136166, 'tmdb_show'), (2051, 'tmdb_show'), (115646, 'tmdb_show'), (1416, 'tmdb_show'), (120089, 'tmdb_show'), (79028, 'tmdb_show'), (93449, 'tmdb_show'), (154911, 'tmdb_show'), (95171, 'tmdb_show'), (135647, 'tmdb_show'), (99966, 'tmdb_show'), (63174, 'tmdb_show'), (1900, 'tmdb_show'), (2024, 'tmdb_show'), (157171, 'tmdb_show'), (202348, 'tmdb_show'), (60735, 'tmdb_show'), (122151, 'tmdb_show'), (456, 'tmdb_show'), (128010, 'tmdb_show'), (103516, 'tmdb_show'), (1402, 'tmdb_show'), (119903, 'tmdb_show'), (71712, 'tmdb_show'), (154571, 'tmdb_show'), (122152, 'tmdb_show'), (2527, 'tmdb_show'), (44953, 'tmdb_show'), (1655, 'tmdb_show'), (1399, 'tmdb_show'), (11250, 'tmdb_show'), (30810, 'tmdb_show'), (155645, 'tmdb_show'), (966, 'tmdb_show'), (2734, 'tmdb_show'), (18165, 'tmdb_show'), (154521, 'tmdb_show'), (80020, 'tmdb_show'), (83215, 'tmdb_show'), (1622, 'tmdb_show'), (95057, 'tmdb_show'), (37680, 'tmdb_show'), (196749, 'tmdb_show'), (158916, 'tmdb_show'), (12971, 'tmdb_show'), (59941, 'tmdb_show'), (77169, 'tmdb_show'), (5920, 'tmdb_show'), (4057, 'tmdb_show'), (94722, 'tmdb_show'), (2224, 'tmdb_show'), (197189, 'tmdb_show'), (62715, 'tmdb_show'), (1408, 'tmdb_show'), (85552, 'tmdb_show'), (43348, 'tmdb_show'), (14750, 'tmdb_show'), (1396, 'tmdb_show'), (86831, 'tmdb_show'), (71790, 'tmdb_show'), (196614, 'tmdb_show'), (65334, 'tmdb_show'), (118663, 'tmdb_show'), (117067, 'tmdb_show'), (46260, 'tmdb_show'), (62286, 'tmdb_show'), (46952, 'tmdb_show'), (93405, 'tmdb_show'), (69050, 'tmdb_show'), (44217, 'tmdb_show'), (104877, 'tmdb_show'), (1434, 'tmdb_show'), (1911, 'tmdb_show'), (123349, 'tmdb_show'), (195871, 'tmdb_show'), (2190, 'tmdb_show'), (81772, 'tmdb_show'), (11890, 'tmdb_show'), (202728, 'tmdb_show'), (79460, 'tmdb_show'), (116135, 'tmdb_show'), (13945, 'tmdb_show'), (4614, 'tmdb_show'), (987, 'tmdb_show'), (81356, 'tmdb_show'), (76669, 'tmdb_show'), (31910, 'tmdb_show'), (31132, 'tmdb_show')] |
[2022-06-11 14:36:56,009] [builder.py:1509]           [DEBUG]    |                                                                                                    |
[2022-06-11 14:36:57,201] [builder.py:1583]           [WARNING]  | Convert Error: No TVDb ID Found for TMDb ID: 154300                                                |
[2022-06-11 14:36:58,344] [builder.py:1583]           [WARNING]  | Convert Error: No TVDb ID Found for TMDb ID: 136166                                                |
[2022-06-11 14:36:59,577] [builder.py:1583]           [WARNING]  | Convert Error: No TVDb ID Found for TMDb ID: 157171                                                |
[2022-06-11 14:37:01,343] [builder.py:1583]           [WARNING]  | Convert Error: No TVDb ID Found for TMDb ID: 202348                                                |
[2022-06-11 14:37:02,947] [builder.py:1583]           [WARNING]  | Convert Error: No TVDb ID Found for TMDb ID: 122151                                                |
[2022-06-11 14:37:04,421] [builder.py:1583]           [WARNING]  | Convert Error: No TVDb ID Found for TMDb ID: 119903                                                |
[2022-06-11 14:37:05,414] [builder.py:1583]           [WARNING]  | Convert Error: No TVDb ID Found for TMDb ID: 122152                                                |
[2022-06-11 14:37:07,301] [builder.py:1583]           [WARNING]  | Convert Error: No TVDb ID Found for TMDb ID: 196614                                                |
[2022-06-11 14:37:08,601] [builder.py:1583]           [WARNING]  | Convert Error: No TVDb ID Found for TMDb ID: 195871                                                |
[2022-06-11 14:37:10,082] [builder.py:1583]           [WARNING]  | Convert Error: No TVDb ID Found for TMDb ID: 202728                                                |
[2022-06-11 14:37:10,107] [builder.py:2009]           [INFO]     |                                                                                                    |
[2022-06-11 14:37:10,108] [builder.py:2010]           [INFO]     |================================ Adding to TMDb Popular Collection =================================|
[2022-06-11 14:37:10,108] [builder.py:2011]           [INFO]     |                                                                                                    |
[2022-06-11 14:37:10,115] [builder.py:2025]           [INFO]     | 1/4 | TMDb Popular Collection | = | The Simpsons                                                   |
[2022-06-11 14:37:10,116] [builder.py:2025]           [INFO]     | 2/4 | TMDb Popular Collection | = | Love, Death & Robots                                           |
[2022-06-11 14:37:10,116] [builder.py:2025]           [INFO]     | 3/4 | TMDb Popular Collection | + | Family Guy                                                     |
[2022-06-11 14:38:10,833] [plex_meta_manager.py:668]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
                                                                 |     six.raise_from(e, None)
                                                                 |   File "<string>", line 3, in raise_from
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
                                                                 |     httplib_response = conn.getresponse()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 1386, in getresponse
                                                                 |     response.begin()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 312, in begin
                                                                 |     version, status, reason = self._read_status()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 273, in _read_status
                                                                 |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                                 |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
                                                                 |     return self._sock.recv_into(b)
                                                                 | socket.timeout: timed out
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
                                                                 |     resp = conn.urlopen(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
                                                                 |     retries = retries.increment(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
                                                                 |     raise six.reraise(type(error), error, _stacktrace)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
                                                                 |     raise value
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
                                                                 |     httplib_response = self._make_request(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
                                                                 |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
                                                                 |     raise ReadTimeoutError(
                                                                 | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "plex_meta_manager.py", line 570, in run_collection
                                                                 |     items_added, items_unchanged = builder.add_to_collection()
                                                                 |   File "/root/Plex-Meta-Manager/modules/builder.py", line 2032, in add_to_collection
                                                                 |     self.library.alter_collection(item, name, smart_label_collection=self.smart_label_collection)
                                                                 |   File "/root/Plex-Meta-Manager/modules/plex.py", line 650, in alter_collection
                                                                 |     field = next((f for f in item.fields if f.name == "collection"), None)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 483, in __getattribute__
                                                                 |     self._reload(_overwriteNone=False)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 357, in _reload
                                                                 |     data = self._server.query(key)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/server.py", line 696, in query
                                                                 |     response = method(url, headers=headers, timeout=timeout, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
                                                                 |     return self.request('GET', url, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
                                                                 |     resp = self.send(prep, **send_kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
                                                                 |     r = adapter.send(request, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
                                                                 |     raise ReadTimeout(e, request=request)
                                                                 | requests.exceptions.ReadTimeout: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
[2022-06-11 14:38:11,240] [plex_meta_manager.py:669]  [ERROR]    | Unknown Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
[2022-06-11 14:38:11,241] [plex_meta_manager.py:674]  [INFO]     | 
[2022-06-11 14:38:11,242] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
[2022-06-11 14:38:11,242] [plex_meta_manager.py:675]  [INFO]     |                                  Finished TMDb Popular Collection                                  |
[2022-06-11 14:38:11,243] [plex_meta_manager.py:675]  [INFO]     |                                    Collection Run Time: 0:01:18                                    |
[2022-06-11 14:38:11,243] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
