[2022-06-10 20:03:52,017] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-10 20:03:52,019] [builder.py:185]            [INFO]     |                         Audio Language Collections Collection in .....综艺节目                         |
[2022-06-10 20:03:52,019] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-10 20:03:52,020] [builder.py:186]            [INFO]     |                                                                                                    |
[2022-06-10 20:03:52,020] [builder.py:191]            [INFO]     |========================= Validating Audio Language Collections Attributes =========================|
[2022-06-10 20:03:52,020] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:03:52,021] [builder.py:213]            [DEBUG]    | Validating Method: template                                                                        |
[2022-06-10 20:03:52,022] [meta.py:103]               [DEBUG]    | Value: [ordereddict([('name', 'separator'), ('separator', 'audio_language')])]                     |
[2022-06-10 20:03:52,026] [builder.py:430]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:03:52,027] [builder.py:431]            [DEBUG]    | Validating Method: blank_collection                                                                |
[2022-06-10 20:03:52,027] [builder.py:432]            [DEBUG]    | Value: True                                                                                        |
[2022-06-10 20:03:52,028] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:03:52,029] [builder.py:604]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-06-10 20:03:52,029] [builder.py:605]            [DEBUG]    | Value: !10_!Audio Language Collections                                                             |
[2022-06-10 20:03:52,030] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:03:52,030] [builder.py:604]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-06-10 20:03:52,030] [builder.py:605]            [DEBUG]    | Value: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/separators/audio_language.jpg |
[2022-06-10 20:03:53,374] [plex.py:742]               [DEBUG]    |                                                                                                    |
[2022-06-10 20:03:53,374] [plex.py:745]               [DEBUG]    | Looking for: Audio Language Collections                                                            |
[2022-06-10 20:03:53,374] [builder.py:764]            [INFO]     |                                                                                                    |
[2022-06-10 20:03:53,375] [builder.py:765]            [INFO]     | Validation Successful                                                                              |
[2022-06-10 20:03:53,375] [plex_meta_manager.py:539]  [INFO]     |                                                                                                    |
[2022-06-10 20:03:53,376] [plex_meta_manager.py:541]  [INFO]     |========================== Running Audio Language Collections Collection ===========================|
[2022-06-10 20:03:56,274] [builder.py:2383]           [INFO]     |                                                                                                    |
[2022-06-10 20:03:56,370] [builder.py:2384]           [INFO]     |==================== Updating Details of Audio Language Collections Collection =====================|
[2022-06-10 20:03:56,370] [builder.py:2385]           [INFO]     |                                                                                                    |
[2022-06-10 20:03:56,371] [builder.py:2446]           [INFO]     | Collection Metadata Edits                                                                          |
                                                                 | Sort Title | !10_!Audio Language Collections
[2022-06-10 20:04:56,934] [plex_meta_manager.py:668]  [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
                                                                 |     six.raise_from(e, None)
                                                                 |   File "<string>", line 3, in raise_from
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
                                                                 |     httplib_response = conn.getresponse()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 1386, in getresponse
                                                                 |     response.begin()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 312, in begin
                                                                 |     version, status, reason = self._read_status()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 273, in _read_status
                                                                 |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                                 |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
                                                                 |     return self._sock.recv_into(b)
                                                                 | socket.timeout: timed out
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
                                                                 |     resp = conn.urlopen(
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
                                                                 |     retries = retries.increment(
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
                                                                 |     raise six.reraise(type(error), error, _stacktrace)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
                                                                 |     raise value
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
                                                                 |     httplib_response = self._make_request(
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
                                                                 |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
                                                                 |     raise ReadTimeoutError(
                                                                 | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/root/Plex-Meta-Manager/plex_meta_manager.py", line 620, in run_collection
                                                                 |     details_list = builder.update_details()
                                                                 |   File "/root/Plex-Meta-Manager/modules/builder.py", line 2449, in update_details
                                                                 |     self.obj.saveEdits()
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/plexapi/base.py", line 594, in saveEdits
                                                                 |     return self.reload()
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/plexapi/base.py", line 348, in reload
                                                                 |     return self._reload(key=key, **kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/plexapi/base.py", line 357, in _reload
                                                                 |     data = self._server.query(key)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/plexapi/server.py", line 696, in query
                                                                 |     response = method(url, headers=headers, timeout=timeout, **kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
                                                                 |     return self.request('GET', url, **kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
                                                                 |     resp = self.send(prep, **send_kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
                                                                 |     r = adapter.send(request, **kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
                                                                 |     raise ReadTimeout(e, request=request)
                                                                 | requests.exceptions.ReadTimeout: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
[2022-06-10 20:04:57,013] [plex_meta_manager.py:669]  [ERROR]    | Unknown Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
[2022-06-10 20:04:57,014] [plex_meta_manager.py:674]  [INFO]     | 
[2022-06-10 20:04:57,015] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
[2022-06-10 20:04:57,015] [plex_meta_manager.py:675]  [INFO]     |                           Finished Audio Language Collections Collection                           |
[2022-06-10 20:04:57,016] [plex_meta_manager.py:675]  [INFO]     |                                    Collection Run Time: 0:01:05                                    |
[2022-06-10 20:04:57,016] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
