[2022-06-10 20:53:15,224] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-10 20:53:15,225] [builder.py:185]            [INFO]     |                              Korean Audio Collection in ....TV Shows                               |
[2022-06-10 20:53:15,225] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-10 20:53:15,226] [builder.py:186]            [INFO]     |                                                                                                    |
[2022-06-10 20:53:15,226] [builder.py:191]            [INFO]     |================================ Validating Korean Audio Attributes ================================|
[2022-06-10 20:53:15,227] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:53:15,227] [builder.py:213]            [DEBUG]    | Validating Method: template                                                                        |
[2022-06-10 20:53:15,229] [meta.py:103]               [DEBUG]    | Value: [{'value': ['ko'], 'audio_language': ['ko'], 'key_name': 'Korean', 'key': 'ko', 'name': 'audio_language_dynamic'}, {'value': ['ko'], 'audio_language': ['ko'], 'key_name': 'Korean', 'key': 'ko', 'name': 'shared'}] |
[2022-06-10 20:53:15,235] [builder.py:1675]           [INFO]     |                                                                                                    |
[2022-06-10 20:53:15,235] [builder.py:1676]           [INFO]     | Validating Method: smart_filter                                                                    |
[2022-06-10 20:53:15,236] [builder.py:1682]           [DEBUG]    | Value: {'sort_by': 'release.desc', 'any': {'audio_language': ['ko']}}                              |
[2022-06-10 20:53:36,711] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:53:36,712] [builder.py:604]            [DEBUG]    | Validating Method: label                                                                           |
[2022-06-10 20:53:36,712] [builder.py:605]            [DEBUG]    | Value: Audio Language                                                                              |
[2022-06-10 20:53:36,715] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:53:36,716] [builder.py:604]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-06-10 20:53:36,716] [builder.py:605]            [DEBUG]    | Value: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/audio_language/ko.jpg |
[2022-06-10 20:53:37,321] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-10 20:53:37,321] [builder.py:604]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-06-10 20:53:37,322] [builder.py:605]            [DEBUG]    | Value: !10_Korean Audio                                                                            |
[2022-06-10 20:53:38,471] [plex.py:742]               [DEBUG]    |                                                                                                    |
[2022-06-10 20:53:38,472] [plex.py:745]               [DEBUG]    | Looking for: Korean Audio                                                                          |
[2022-06-10 20:53:38,472] [builder.py:764]            [INFO]     |                                                                                                    |
[2022-06-10 20:53:38,472] [builder.py:765]            [INFO]     | Validation Successful                                                                              |
[2022-06-10 20:53:38,473] [plex_meta_manager.py:539]  [INFO]     |                                                                                                    |
[2022-06-10 20:53:38,473] [plex_meta_manager.py:541]  [INFO]     |================================= Running Korean Audio Collection ==================================|
[2022-06-10 20:53:38,473] [plex_meta_manager.py:547]  [INFO]     |                                                                                                    |
[2022-06-10 20:53:38,474] [plex_meta_manager.py:548]  [INFO]     | Smart Show Filter                                                                                  |
                                                                 | Sort By: release.desc
                                                                 | Filter:
                                                                 |   Match any of the following:
                                                                 |     Audio Language is ko
[2022-06-10 20:53:42,181] [plex.py:664]               [DEBUG]    | Smart Collection Test: ?type=2&sort=originallyAvailableAt%3Adesc&push=1&episode.audioLanguage=ko&pop=1
[2022-06-10 21:00:33,142] [plex_meta_manager.py:668]  [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
                                                                 |     six.raise_from(e, None)
                                                                 |   File "<string>", line 3, in raise_from
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
                                                                 |     httplib_response = conn.getresponse()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 1386, in getresponse
                                                                 |     response.begin()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 312, in begin
                                                                 |     version, status, reason = self._read_status()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 273, in _read_status
                                                                 |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                                 |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
                                                                 |     return self._sock.recv_into(b)
                                                                 | socket.timeout: timed out
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
                                                                 |     resp = conn.urlopen(
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
                                                                 |     retries = retries.increment(
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
                                                                 |     raise six.reraise(type(error), error, _stacktrace)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
                                                                 |     raise value
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
                                                                 |     httplib_response = self._make_request(
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
                                                                 |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
                                                                 |     raise ReadTimeoutError(
                                                                 | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/root/Plex-Meta-Manager/plex_meta_manager.py", line 607, in run_collection
                                                                 |     builder.load_collection()
                                                                 |   File "/root/Plex-Meta-Manager/modules/builder.py", line 2365, in load_collection
                                                                 |     self.library.create_smart_collection(self.name, self.smart_type_key, self.smart_url)
                                                                 |   File "/root/Plex-Meta-Manager/modules/plex.py", line 678, in create_smart_collection
                                                                 |     self._query(f"/library/collections{utils.joinArgs(args)}", post=True)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
                                                                 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/retrying.py", line 212, in call
                                                                 |     raise attempt.get()
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/retrying.py", line 247, in get
                                                                 |     six.reraise(self.value[0], self.value[1], self.value[2])
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/six.py", line 719, in reraise
                                                                 |     raise value
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/retrying.py", line 200, in call
                                                                 |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                                                                 |   File "/root/Plex-Meta-Manager/modules/plex.py", line 612, in _query
                                                                 |     return self.Plex._server.query(key, method=method)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/plexapi/server.py", line 696, in query
                                                                 |     response = method(url, headers=headers, timeout=timeout, **kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/sessions.py", line 577, in post
                                                                 |     return self.request('POST', url, data=data, json=json, **kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
                                                                 |     resp = self.send(prep, **send_kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
                                                                 |     r = adapter.send(request, **kwargs)
                                                                 |   File "/root/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
                                                                 |     raise ReadTimeout(e, request=request)
                                                                 | requests.exceptions.ReadTimeout: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
[2022-06-10 21:00:33,169] [plex_meta_manager.py:669]  [ERROR]    | Unknown Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
[2022-06-10 21:00:33,170] [plex_meta_manager.py:674]  [INFO]     | 
[2022-06-10 21:00:33,171] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
[2022-06-10 21:00:33,171] [plex_meta_manager.py:675]  [INFO]     |                                  Finished Korean Audio Collection                                  |
[2022-06-10 21:00:33,172] [plex_meta_manager.py:675]  [INFO]     |                                    Collection Run Time: 0:07:17                                    |
[2022-06-10 21:00:33,172] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
