[2022-06-11 13:47:20,274] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 13:47:20,403] [builder.py:185]            [INFO]     |                              Best of 1990s Collection in ....TV Shows                              |
[2022-06-11 13:47:20,499] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 13:47:20,499] [builder.py:186]            [INFO]     |                                                                                                    |
[2022-06-11 13:47:20,500] [builder.py:191]            [INFO]     |=============================== Validating Best of 1990s Attributes ================================|
[2022-06-11 13:47:20,500] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2022-06-11 13:47:20,501] [builder.py:213]            [DEBUG]    | Validating Method: template                                                                        |
[2022-06-11 13:47:20,502] [meta.py:103]               [DEBUG]    | Value: [{'value': [1997, 1991, 1995, 1990, 1992], 'decade': [1997, 1991, 1995, 1990, 1992], 'key_name': '1990', 'key': '1990', 'name': 'decade_dynamic'}, {'value': [1997, 1991, 1995, 1990, 1992], 'decade': [1997, 1991, 1995, 1990, 1992], 'key_name': '1990', 'key': '1990', 'name': 'shared'}] |
[2022-06-11 13:47:20,505] [builder.py:1675]           [INFO]     |                                                                                                    |
[2022-06-11 13:47:20,506] [builder.py:1676]           [INFO]     | Validating Method: smart_filter                                                                    |
[2022-06-11 13:47:20,506] [builder.py:1682]           [DEBUG]    | Value: {'sort_by': 'critic_rating.desc', 'any': {'year': [1997, 1991, 1995, 1990, 1992]}, 'limit': 100} |
[2022-06-11 13:47:20,508] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 13:47:20,509] [builder.py:604]            [DEBUG]    | Validating Method: label                                                                           |
[2022-06-11 13:47:20,509] [builder.py:605]            [DEBUG]    | Value: Decade                                                                                      |
[2022-06-11 13:47:20,510] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 13:47:20,511] [builder.py:604]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-06-11 13:47:20,511] [builder.py:605]            [DEBUG]    | Value: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/decade/best/1990.jpg |
[2022-06-11 13:47:20,823] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 13:47:20,823] [builder.py:604]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-06-11 13:47:20,824] [builder.py:605]            [DEBUG]    | Value: !12_Best of 1990s                                                                           |
[2022-06-11 13:47:21,141] [plex.py:742]               [DEBUG]    |                                                                                                    |
[2022-06-11 13:47:21,142] [plex.py:745]               [DEBUG]    | Looking for: Best of 1990s                                                                         |
[2022-06-11 13:47:21,142] [builder.py:764]            [INFO]     |                                                                                                    |
[2022-06-11 13:47:21,143] [builder.py:765]            [INFO]     | Validation Successful                                                                              |
[2022-06-11 13:47:21,143] [plex_meta_manager.py:539]  [INFO]     |                                                                                                    |
[2022-06-11 13:47:21,144] [plex_meta_manager.py:541]  [INFO]     |================================= Running Best of 1990s Collection =================================|
[2022-06-11 13:47:21,145] [plex_meta_manager.py:547]  [INFO]     |                                                                                                    |
[2022-06-11 13:47:21,145] [plex_meta_manager.py:548]  [INFO]     | Smart Show Filter                                                                                  |
                                                                 | Sort By: critic_rating.desc
                                                                 | Limit: 100
                                                                 | Filter:
                                                                 |   Match any of the following:
                                                                 |     Year is 1997
                                                                 |     Year is 1991
                                                                 |     Year is 1995
                                                                 |     Year is 1990
                                                                 |     Year is 1992
[2022-06-11 13:47:21,689] [plex.py:664]               [DEBUG]    | Smart Collection Test: ?type=2&limit=100&sort=rating%3Adesc&push=1&show.year=1997&or=1&show.year=1991&or=1&show.year=1995&or=1&show.year=1990&or=1&show.year=1992&pop=1
[2022-06-11 13:47:32,737] [builder.py:2383]           [INFO]     | 
[2022-06-11 13:47:32,972] [builder.py:2384]           [INFO]     |=========================== Updating Details of Best of 1990s Collection ===========================|
[2022-06-11 13:47:32,972] [builder.py:2385]           [INFO]     |                                                                                                    |
[2022-06-11 13:48:33,279] [plex_meta_manager.py:668]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
                                                                 |     six.raise_from(e, None)
                                                                 |   File "<string>", line 3, in raise_from
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
                                                                 |     httplib_response = conn.getresponse()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 1386, in getresponse
                                                                 |     response.begin()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 312, in begin
                                                                 |     version, status, reason = self._read_status()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 273, in _read_status
                                                                 |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                                 |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
                                                                 |     return self._sock.recv_into(b)
                                                                 | socket.timeout: timed out
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
                                                                 |     resp = conn.urlopen(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
                                                                 |     retries = retries.increment(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
                                                                 |     raise six.reraise(type(error), error, _stacktrace)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
                                                                 |     raise value
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
                                                                 |     httplib_response = self._make_request(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
                                                                 |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
                                                                 |     raise ReadTimeoutError(
                                                                 | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "plex_meta_manager.py", line 620, in run_collection
                                                                 |     details_list = builder.update_details()
                                                                 |   File "/root/Plex-Meta-Manager/modules/builder.py", line 2442, in update_details
                                                                 |     tag_results = self.library.edit_tags('label', self.obj, add_tags=add_tags, remove_tags=remove_tags, sync_tags=sync_tags, do_print=False)[28:]
                                                                 |   File "/root/Plex-Meta-Manager/modules/plex.py", line 875, in edit_tags
                                                                 |     _item_tags = [item_tag.tag for item_tag in getattr(obj, key)]
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 483, in __getattribute__
                                                                 |     self._reload(_overwriteNone=False)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 357, in _reload
                                                                 |     data = self._server.query(key)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/server.py", line 696, in query
                                                                 |     response = method(url, headers=headers, timeout=timeout, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
                                                                 |     return self.request('GET', url, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
                                                                 |     resp = self.send(prep, **send_kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
                                                                 |     r = adapter.send(request, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
                                                                 |     raise ReadTimeout(e, request=request)
                                                                 | requests.exceptions.ReadTimeout: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
[2022-06-11 13:48:33,361] [plex_meta_manager.py:669]  [ERROR]    | Unknown Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
[2022-06-11 13:48:33,362] [plex_meta_manager.py:674]  [INFO]     | 
[2022-06-11 13:48:33,362] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
[2022-06-11 13:48:33,363] [plex_meta_manager.py:675]  [INFO]     |                                 Finished Best of 1990s Collection                                  |
[2022-06-11 13:48:33,364] [plex_meta_manager.py:675]  [INFO]     |                                    Collection Run Time: 0:01:13                                    |
[2022-06-11 13:48:33,364] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
