[2022-06-11 10:29:59,353] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 10:29:59,355] [builder.py:185]            [INFO]     |                                Trakt Trending Collection in Movies                                 |
[2022-06-11 10:29:59,356] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 10:29:59,357] [builder.py:186]            [INFO]     |                                                                                                    |
[2022-06-11 10:29:59,358] [builder.py:191]            [INFO]     |=============================== Validating Trakt Trending Attributes ===============================|
[2022-06-11 10:29:59,359] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:29:59,360] [builder.py:213]            [DEBUG]    | Validating Method: template                                                                        |
[2022-06-11 10:29:59,363] [meta.py:103]               [DEBUG]    | Value: [{'value': ['trending'], 'custom': ['trending'], 'key_name': 'Trending', 'key': 'trending', 'name': 'trakt'}, {'value': ['trending'], 'custom': ['trending'], 'key_name': 'Trending', 'key': 'trending', 'name': 'customsync'}, {'value': ['trending'], 'custom': ['trending'], 'key_name': 'Trending', 'key': 'trending', 'name': 'chart_shared'}] |
[2022-06-11 10:29:59,374] [builder.py:437]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:29:59,375] [builder.py:438]            [DEBUG]    | Validating Method: sync_mode                                                                       |
[2022-06-11 10:29:59,376] [builder.py:442]            [DEBUG]    | Value: sync                                                                                        |
[2022-06-11 10:29:59,376] [builder.py:582]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:29:59,377] [builder.py:583]            [DEBUG]    | Validating Method: collection_order                                                                |
[2022-06-11 10:29:59,378] [builder.py:584]            [DEBUG]    | Value: custom                                                                                      |
[2022-06-11 10:29:59,378] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:29:59,380] [builder.py:604]            [DEBUG]    | Validating Method: label                                                                           |
[2022-06-11 10:29:59,380] [builder.py:605]            [DEBUG]    | Value: Trakt                                                                                       |
[2022-06-11 10:29:59,381] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:29:59,382] [builder.py:604]            [DEBUG]    | Validating Method: trakt_chart                                                                     |
[2022-06-11 10:29:59,383] [builder.py:605]            [DEBUG]    | Value: {'chart': 'trending', 'limit': 100}                                                         |
[2022-06-11 10:29:59,387] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:29:59,387] [builder.py:604]            [DEBUG]    | Validating Method: summary                                                                         |
[2022-06-11 10:29:59,388] [builder.py:605]            [DEBUG]    | Value: A collection of Trakt's Weekly movie List                                                   |
[2022-06-11 10:29:59,389] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:29:59,390] [builder.py:604]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-06-11 10:29:59,390] [builder.py:605]            [DEBUG]    | Value: !01_Trakt Trending                                                                          |
[2022-06-11 10:29:59,391] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:29:59,392] [builder.py:604]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-06-11 10:29:59,392] [builder.py:605]            [DEBUG]    | Value: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/chart/Trakt%20Trending.jpg |
[2022-06-11 10:30:00,230] [plex.py:742]               [DEBUG]    |                                                                                                    |
[2022-06-11 10:30:00,231] [plex.py:745]               [DEBUG]    | Looking for: Trakt Trending                                                                        |
[2022-06-11 10:30:00,232] [builder.py:764]            [INFO]     |                                                                                                    |
[2022-06-11 10:30:00,233] [builder.py:765]            [INFO]     | Validation Successful                                                                              |
[2022-06-11 10:30:00,234] [plex_meta_manager.py:539]  [INFO]     |                                                                                                    |
[2022-06-11 10:30:00,234] [plex_meta_manager.py:541]  [INFO]     |================================ Running Trakt Trending Collection =================================|
[2022-06-11 10:30:00,236] [plex_meta_manager.py:553]  [INFO]     |                                                                                                    |
[2022-06-11 10:30:00,237] [plex_meta_manager.py:554]  [INFO]     | Sync Mode: sync                                                                                    |
[2022-06-11 10:30:00,238] [plex_meta_manager.py:557]  [DEBUG]    |                                                                                                    |
[2022-06-11 10:30:00,239] [plex_meta_manager.py:558]  [DEBUG]    | Builder: trakt_chart: {'chart': 'trending', 'limit': 100, 'time_period': None}                     |
[2022-06-11 10:30:00,240] [plex_meta_manager.py:559]  [INFO]     |                                                                                                    |
[2022-06-11 10:30:00,242] [trakt.py:490]              [INFO]     | Processing Trakt Chart: 100 Trending Movies                                                        |
[2022-06-11 10:30:01,378] [builder.py:1507]           [DEBUG]    |                                                                                                    |
[2022-06-11 10:30:02,666] [builder.py:1508]           [DEBUG]    | 100 IDs Found: [(648579, 'tmdb'), (820446, 'tmdb'), (545611, 'tmdb'), (338953, 'tmdb'), (705861, 'tmdb'), (752623, 'tmdb'), (639933, 'tmdb'), (361743, 'tmdb'), (809140, 'tmdb'), (675353, 'tmdb'), (526896, 'tmdb'), (507086, 'tmdb'), (744, 'tmdb'), (961484, 'tmdb'), (414906, 'tmdb'), (629542, 'tmdb'), (329, 'tmdb'), (351286, 'tmdb'), (335787, 'tmdb'), (763285, 'tmdb'), (135397, 'tmdb'), (818397, 'tmdb'), (425909, 'tmdb'), (505026, 'tmdb'), (634649, 'tmdb'), (370172, 'tmdb'), (800937, 'tmdb'), (532710, 'tmdb'), (957258, 'tmdb'), (330, 'tmdb'), (438695, 'tmdb'), (831946, 'tmdb'), (259316, 'tmdb'), (22, 'tmdb'), (211672, 'tmdb'), (546554, 'tmdb'), (453395, 'tmdb'), (628900, 'tmdb'), (58, 'tmdb'), (550988, 'tmdb'), (56292, 'tmdb'), (524434, 'tmdb'), (624860, 'tmdb'), (9571, 'tmdb'), (626735, 'tmdb'), (689700, 'tmdb'), (579974, 'tmdb'), (923597, 'tmdb'), (739643, 'tmdb'), (846250, 'tmdb'), (19995, 'tmdb'), (49051, 'tmdb'), (674, 'tmdb'), (1892, 'tmdb'), (181808, 'tmdb'), (1895, 'tmdb'), (238, 'tmdb'), (1271, 'tmdb'), (187, 'tmdb'), (404368, 'tmdb'), (464052, 'tmdb'), (512195, 'tmdb'), (696806, 'tmdb'), (406759, 'tmdb'), (597208, 'tmdb'), (379686, 'tmdb'), (614917, 'tmdb'), (656663, 'tmdb'), (615904, 'tmdb'), (420821, 'tmdb'), (294793, 'tmdb'), (661231, 'tmdb'), (592695, 'tmdb'), (916821, 'tmdb'), (872177, 'tmdb'), (843633, 'tmdb'), (962279, 'tmdb'), (293660, 'tmdb'), (155, 'tmdb'), (157336, 'tmdb'), (315635, 'tmdb'), (245891, 'tmdb'), (100402, 'tmdb'), (299534, 'tmdb'), (70160, 'tmdb'), (672, 'tmdb'), (585, 'tmdb'), (9806, 'tmdb'), (299537, 'tmdb'), (57158, 'tmdb'), (597, 'tmdb'), (297802, 'tmdb'), (343611, 'tmdb'), (47933, 'tmdb'), (18, 'tmdb'), (13183, 'tmdb'), (438631, 'tmdb'), (353081, 'tmdb'), (497698, 'tmdb'), (332562, 'tmdb')] |
[2022-06-11 10:30:02,667] [builder.py:1509]           [DEBUG]    |                                                                                                    |
[2022-06-11 10:30:02,692] [builder.py:2009]           [INFO]     |                                                                                                    |
[2022-06-11 10:30:02,693] [builder.py:2010]           [INFO]     |=============================== Adding to Trakt Trending Collection ================================|
[2022-06-11 10:30:02,694] [builder.py:2011]           [INFO]     |                                                                                                    |
[2022-06-11 10:30:02,695] [builder.py:2025]           [INFO]     |  1/11 | Trakt Trending Collection | + | Sing 2 (2021)                                              |
[2022-06-11 10:31:02,774] [plex_meta_manager.py:668]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
                                                                 |     six.raise_from(e, None)
                                                                 |   File "<string>", line 3, in raise_from
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
                                                                 |     httplib_response = conn.getresponse()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 1386, in getresponse
                                                                 |     response.begin()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 312, in begin
                                                                 |     version, status, reason = self._read_status()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 273, in _read_status
                                                                 |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                                 |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
                                                                 |     return self._sock.recv_into(b)
                                                                 | socket.timeout: timed out
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
                                                                 |     resp = conn.urlopen(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
                                                                 |     retries = retries.increment(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
                                                                 |     raise six.reraise(type(error), error, _stacktrace)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
                                                                 |     raise value
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
                                                                 |     httplib_response = self._make_request(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
                                                                 |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
                                                                 |     raise ReadTimeoutError(
                                                                 | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "plex_meta_manager.py", line 570, in run_collection
                                                                 |     items_added, items_unchanged = builder.add_to_collection()
                                                                 |   File "/root/Plex-Meta-Manager/modules/builder.py", line 2032, in add_to_collection
                                                                 |     self.library.alter_collection(item, name, smart_label_collection=self.smart_label_collection)
                                                                 |   File "/root/Plex-Meta-Manager/modules/plex.py", line 650, in alter_collection
                                                                 |     field = next((f for f in item.fields if f.name == "collection"), None)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 483, in __getattribute__
                                                                 |     self._reload(_overwriteNone=False)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 357, in _reload
                                                                 |     data = self._server.query(key)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/server.py", line 696, in query
                                                                 |     response = method(url, headers=headers, timeout=timeout, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
                                                                 |     return self.request('GET', url, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
                                                                 |     resp = self.send(prep, **send_kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
                                                                 |     r = adapter.send(request, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
                                                                 |     raise ReadTimeout(e, request=request)
                                                                 | requests.exceptions.ReadTimeout: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
[2022-06-11 10:31:02,790] [plex_meta_manager.py:669]  [ERROR]    | Unknown Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
[2022-06-11 10:31:02,791] [plex_meta_manager.py:674]  [INFO]     | 
[2022-06-11 10:31:02,791] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
[2022-06-11 10:31:02,793] [plex_meta_manager.py:675]  [INFO]     |                                 Finished Trakt Trending Collection                                 |
[2022-06-11 10:31:02,793] [plex_meta_manager.py:675]  [INFO]     |                                    Collection Run Time: 0:01:04                                    |
[2022-06-11 10:31:02,793] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
